import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidelinesSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Introduction',
      link: {type: 'generated-index', slug: 'category/introduction'},
      items: [{type: 'autogenerated', dirName: 'Introduction'}],
    },
    {
      type: 'category',
      label: 'Patient Assessment',
      link: {type: 'generated-index', slug: 'category/patient-assessment'},
      items: [{type: 'autogenerated', dirName: 'Assessment'}],
    },
    {
      type: 'category',
      label: 'Emergency',
      link: {type: 'generated-index', slug: 'category/emergency'},
      items: [{type: 'autogenerated', dirName: 'Emergency'}],
    },
    {
      type: 'category',
      label: 'Medical Conditions',
      link: {type: 'generated-index', slug: 'category/medical-conditions'},
      items: [{type: 'autogenerated', dirName: 'Medical'}],
    },
    {
      type: 'category',
      label: 'Maternal & Gynecological',
      link: {type: 'generated-index', slug: 'category/maternal-gynecological'},
      items: [{type: 'autogenerated', dirName: 'Maternal'}],
    },
    {
      type: 'category',
      label: 'Pediatrics',
      link: {type: 'generated-index', slug: 'category/pediatrics'},
      items: [{type: 'autogenerated', dirName: 'Pediatrics'}],
    },
    {
      type: 'category',
      label: 'Skin Conditions',
      link: {type: 'generated-index', slug: 'category/skin-conditions'},
      items: [{type: 'autogenerated', dirName: 'Skin'}],
    },
    {
      type: 'category',
      label: 'Infectious Diseases',
      link: {type: 'generated-index', slug: 'category/infectious-diseases'},
      items: [{type: 'autogenerated', dirName: 'Infectious-Diseases'}],
    },
    {
      type: 'category',
      label: 'Appendix',
      link: {type: 'generated-index', slug: 'category/appendix'},
      items: [{type: 'autogenerated', dirName: 'Appendix'}],
    },
    {
      type: 'category',
      label: 'Nursing Procedures',
      link: {type: 'generated-index', slug: 'category/nursing-procedures'},
      items: [{type: 'autogenerated', dirName: 'Nursing'}],
    },
  ],
};

export default sidebars;
