import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidelinesSidebar: [
    'Criteria for early notification of trauma',
    'intro',
  
    {
      type: 'category',
      label: 'Introduction',
      link: {type: 'generated-index', slug: 'category/introduction'},
      items: [{type: 'autogenerated', dirName: 'Introduction'}],
    },
    {
      type: 'category',
      label: 'Patient assessment and transport',
      link: {type: 'generated-index', slug: 'category/Patient assessment and transport'},
      items: [{type: 'autogenerated', dirName: 'Patient assessment and transport'}],
    },
    {
      type: 'category',
      label: 'Pain, nausea and vomiting',
      link: {type: 'generated-index', slug: 'category/pain-nausea-vomiting'},
      items: [{type: 'autogenerated', dirName: 'Pain, nausea and vomiting'}],
    },
    {
      type: 'category',
      label: 'Emergency',
      link: {type: 'generated-index', slug: 'category/emergency'},
      items: [{type: 'autogenerated', dirName: 'Emergency'}],
    },
    {
      type: 'category',
      label: 'Common medical conditions',
      link: {type: 'generated-index', slug: 'category/medical-conditions'},
      items: [{type: 'autogenerated', dirName: 'Medical'}],
    },
    {
      type: 'category',
      label: 'Cardiovascular and respiratory disorders',
      link: {type: 'generated-index', slug: 'category/Cardiovascular and respiratory'},
      items: [{type: 'autogenerated', dirName: 'Cardiovascular and respiratory disorders'}],
    },
    {
      type: 'category',
      label: 'Ear, Nose and Throat (ENT)',
      link: {type: 'generated-index', slug: 'category/ENT'},
      items: [{type: 'autogenerated', dirName: 'ENT'}],
    },
    {
      type: 'category',
      label: 'Oral health',
      link: {type: 'generated-index', slug: 'category/Oral health'},
      items: [{type: 'autogenerated', dirName: 'Oral health'}],
    },
    {
      type: 'category',
      label: 'Eye problems',
      link: {type: 'generated-index', slug: 'category/Eye problems'},
      items: [{type: 'autogenerated', dirName: 'Eye problems'}],
    },
    {
      type: 'category',
      label: 'Gastrointestinal',
      link: {type: 'generated-index', slug: 'category/Gastrointestinal'},
      items: [{type: 'autogenerated', dirName: 'Gastrointestinal'}],
    },
    {
      type: 'category',
      label: 'Obstetric and Gynecological',
      link: {type: 'generated-index', slug: 'category/Obstetric/Gynecological'},
      items: [{type: 'autogenerated', dirName: 'Obstetric and Gynecological'}],
    },
    {
      type: 'category',
      label: 'Genitourinary emergencies',
      link: {type: 'generated-index', slug: 'category/Genitourinary emergencies'},
      items: [{type: 'autogenerated', dirName: 'Genitourinary emergencies'}],
    },
    {
      type: 'category',
      label: 'Mental health',
      link: {type: 'generated-index', slug: 'category/Mental health'},
      items: [{type: 'autogenerated', dirName: 'Mental health'}],
    },
    {
      type: 'category',
      label: 'Paediatrics',
      link: {type: 'generated-index', slug: 'category/Paediatrics'},
      items: [{type: 'autogenerated', dirName: 'Paediatrics'}],
    },
    {
      type: 'category',
      label: 'Skin problems',
      link: {type: 'generated-index', slug: 'category/Skin problems'},
      items: [{type: 'autogenerated', dirName: 'Skin problems'}],
    },
    {
      type: 'category',
      label: 'Infectious diseases',
      link: {type: 'generated-index', slug: 'category/Infectious diseases'},
      items: [{type: 'autogenerated', dirName: 'Infectious diseases'}],
    },
    {
      type: 'category',
      label: 'Appendix',
      link: {type: 'generated-index', slug: 'category/Appendix'},
      items: [{type: 'autogenerated', dirName: 'Appendix'}],
    },
    {
      type: 'category',
      label: 'Safe use of Drugs, Including Antibiotic Use',
      link: {type: 'generated-index', slug: 'category/Safe use of Drugs, Including Antibiotic Use'},
      items: [{type: 'autogenerated', dirName: 'Safe use of Drugs, Including Antibiotic Use'}],
    },
    {
      type: 'category',
      label: 'List of Abbreviations and Acronyms',
      link: {type: 'generated-index', slug: 'category/Abbreviations & Acronyms'},
      items: [{type: 'autogenerated', dirName: 'List of Abbreviations and Acronyms'}],
    },
  ],
};

export default sidebars;
