# Apache virtual host for WAMP
# Installed by: npm run setup:wamp

<VirtualHost *:80>
    ServerName clinical-guidelines.local
    DocumentRoot "C:/wamp64/www/Projects/2026/clinical-guidelines"
    <Directory "C:/wamp64/www/Projects/2026/clinical-guidelines">
        Options +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
